<maininterface>:
maininterface:
#Example 1
    # Button:
    #     text: "Button 1"

    # Button:
    #     text: "Buton 2"

    # Button:
    #     text: "Button 3"

#Exapmle 2
    orientation: "vertical"
    Button:
        text: "Button 1"
        size_hint: 0.3,0.6
    Button:
        text: "Button 2"
        size_hint: None, None
        size: 500,300
    Button:
        text: "Button 3"
        size_hint_y: None
        size_hint_x: 0.6