Scrollerfn:
<Scrollerfn@ScrollView>:
    bar_margin: 20  #Chaging bar mergin from right side
    bar_color: 0.3,0.6,0.4,1 #Color of bar
    bar_width: 10
    # bar_height: 10 # its not working
    bar_inactive_color: 1,0,0,1
    Interface:
        size_hint: 1, None  # Givin scrling type Horizontal or Vertical 
        # height: 4000        # Height of the scroll for vertical scrling if horizintal give width
        height: self.minimum_height # Scrol with minimum height 
<Interface>:
    padding: 20
    spacing: 10