<Interface>:
Interface:
    Button:
        text: "Red Button"
        size: 150,150
        pos: 200, 350
        background_color: (1, 0, 0, 1)
        background_normal: ""

    Button:
        text: "Green Button"
        size: 150,150
        pos: 400, 350
        background_color: (0, 1, 0, 1)
        background_normal: ""
    Button:
        text: "Blue Button"
        size: 150,150
        pos: 600,350
        background_color: (0, 0, 1, 1)
        background_normal: ""
    Label:
        markup: True
        text: "Label 1"
        pos: 200, 500
        size: 150,150
        font_size: 20
    
    Label:
        markup: True
        size: "Label 2"
        pos: 0,0
        size: 150,150
        font_size: 20

    Label: 
        markup: True
        size: "Label 3"
        pos: 600, 500
        size: 150,150
        font_size: 20
